name: Commit and Push
description: Commit local changes (if any) and push to the caller's branch using a PAT.

inputs:
  pat:
    description: Personal Access Token with permission to push commits
    required: true
  message:
    description: Base commit message (labels will be appended as bracketed tags)
    required: false
    default: "style: apply autofix"
  labels:
    description: Labels to append as [label] tags (comma or space separated). Labels from the previous commit are also inherited automatically.
    required: false
    default: autofix

outputs:
  has_changes:
    description: Whether there were changes to commit
    value: ${{ steps.commit.outputs.has_changes || 'false' }}
  did_push:
    description: Whether a push was performed
    value: ${{ steps.push.outputs.did_push || 'false' }}

runs:
  using: composite
  steps:
    - name: Configure Git user
      uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/actions/git-config@main

    - name: Commit changes if any
      id: commit
      shell: bash
      run: |
        bash "${GITHUB_ACTION_PATH}/commit-changes.sh" \
          "${{ inputs.message }}" \
          "${{ inputs.labels }}"

    - name: Push changes
      id: push
      if: steps.commit.outputs.has_changes == 'true' && inputs.pat != ''
      shell: bash
      env:
        PAT: ${{ inputs.pat }}
      run: |
        bash "${GITHUB_ACTION_PATH}/push-changes.sh" \
          "${PAT}" \
          "${{ github.repository }}" \
          "${{ github.head_ref || github.ref_name }}"
