name: Find Release Cuts
description: Determine the current and previous release cut points on dev based on main's latest x.y.0 tag.

inputs:
  dev_branch:
    description: Name of the development branch
    required: false
    default: dev
  main_branch:
    description: Name of the main branch
    required: false
    default: main

outputs:
  cur_cut:
    description: Current release cut (fork point from dev to HEAD)
    value: ${{ steps.run.outputs.cur_cut }}
  prev_cut:
    description: Previous release cut (fork point from dev to latest x.y.0 tag merge)
    value: ${{ steps.run.outputs.prev_cut }}

runs:
  using: composite
  steps:
    - name: Compute release cuts
      id: run
      shell: bash
      env:
        DEV_BRANCH: ${{ inputs.dev_branch }}
        MAIN_BRANCH: ${{ inputs.main_branch }}
      run: |
        bash "${GITHUB_ACTION_PATH}/find-release-cuts.sh"
