name: Configure Git User
description: Set git user.name and user.email for subsequent git operations.

inputs:
  name:
    description: Git user.name to set
    required: false
    default: github-actions[bot]
  email:
    description: Git user.email to set
    required: false
    default: 41898282+github-actions[bot]@users.noreply.github.com

runs:
  using: composite
  steps:
    - name: Configure git user
      shell: bash
      run: |
        git config user.name "${{ inputs.name }}"
        git config user.email "${{ inputs.email }}"
