name: Verify installed package version
description: Compare installed package version with expected string
inputs:
  package:
    description: Package import/distribution name
    required: true
  expected:
    description: Expected version string
    required: true
runs:
  using: composite
  steps:
    - name: Verify installed version
      shell: bash
      env:
        PKG: ${{ inputs.package }}
        EXPECTED: ${{ inputs.expected }}
      run: |
        bash "${GITHUB_ACTION_PATH}/verify-version.sh" \
          "${PKG}" \
          "${EXPECTED}"
