name: Get Last Changelog Version
description: Read CHANGELOG.rst and output the last recorded version tag (vX.Y.Z) from the latest entry header. Returns v0.0.0 if no version exists.

inputs:
  changelog_path:
    description: Path to the changelog file
    required: false
    default: CHANGELOG.rst

outputs:
  last_tag:
    description: Last version tag found in the changelog (vX.Y.Z), or v0.0.0 if none
    value: ${{ steps.extract.outputs.last_tag }}

runs:
  using: composite
  steps:
    - name: Determine last CHANGELOG version
      id: extract
      shell: bash
      env:
        CHANGELOG_PATH: ${{ inputs.changelog_path }}
      run: |
        bash "${GITHUB_ACTION_PATH}/get-last-changelog-version.sh" \
          "${CHANGELOG_PATH}"
