name: dev_pr

on:
  workflow_call:
    secrets:
      PAT_AUTOFIX:
        required: true


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    outputs:
      did_push: ${{ steps.format.outputs.did_push || 'false' }}
    steps:
      - name: Run format action
        id: format
        uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/actions/format@main
        with:
          pat_autofix: ${{ secrets.PAT_AUTOFIX }}

  test:
    name: test
    runs-on: ubuntu-latest
    needs: format
    if: needs.format.outputs.did_push != 'true'
    steps:
      - name: Run test action
        uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/actions/test@main
